# Generated by Django 4.2.9 on 2024-02-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employeeproject_projectid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeproject',
            name='projectID',
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='projectID',
            field=models.ManyToManyField(help_text='Назнач проект', to='app.projects'),
        ),
    ]
