# Generated by Django 4.2.9 on 2024-02-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_employeeproject_projectid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeproject',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='employeeproject',
            name='projectID',
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(default=0, help_text='Назначьте сотрудника', on_delete=django.db.models.deletion.CASCADE, to='app.employees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(default=1, help_text='Назначьте проект', on_delete=django.db.models.deletion.CASCADE, to='app.projects'),
            preserve_default=False,
        ),
    ]
