# Generated by Django 4.2.9 on 2024-02-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_employeeproject_employeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproject',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
