# Generated by Django 4.2.9 on 2024-02-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employeeproject_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(help_text='Назначьте сотрудника', on_delete=django.db.models.deletion.CASCADE, to='app.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeproject',
            name='project',
            field=models.ForeignKey(help_text='Назначьте проект', on_delete=django.db.models.deletion.CASCADE, to='app.projects', verbose_name='Проект'),
        ),
    ]
