# Generated by Django 4.2.9 on 2024-02-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
