# Generated by Django 4.2.9 on 2024-02-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
